### PR TITLE
Added ability to automatically detect and work with 50Hz or 60Hz mains without code changes

### PR DESCRIPTION
**Pull request by canidorichard**
Added ability to automatically detect and work with 50Hz or 60Hz mains without code changes defaulting to 60Hz if detection is not completed.  This should be backward compatible with previous version.

Renamed x10_bink.pde to x10_blink.ino as the .pde extension is legacy.
Renamed x10_fade.pde to x10_fade.ino as the .pde extension is legacy.
Renamed x10_multi.pde to x10_multi.ino  as the .pde extension is legacy.
Renamed x10_receive.pde to x10_receive.ino  as the .pde extension is legacy.

x10_blink.ino:
  - Initialise the x10 object inside the setup loop rather than when created to allow for auto mains frequency detection.

x10_fade.ino:
  - Changed reference to A to be HOUSE_A in Setup() as it looks like this was missed when other instances were changed causing a compilation failure as A is not defined.
  - Initialise the x10 object inside the setup loop rather than when created to allow for auto mains frequency detection.

x10_multi:
  - Removed undefined variable from Serial.begin(dataRate) and replaced with Serial.begin(57600) in line with other examples.
  - Removed reference to RFID to X10 reader which has no relation to the example.
  - Changed reference to A to be HOUSE_A in Setup() as it looks like this was missed when other instances were changed causing a compilation failure as A is not defined.
  - Initialise the x10 object inside the setup loop rather than when created to allow for auto mains frequency detection.

x10_receive:
  - Removed include for WProgram.h as this is legacy and prevents compilation in current versions of the Arduino IDE.
  - Initialise the x10 object inside the setup loop rather than when created to allow for auto mains frequency detection.

x10constants.h: 2017-APR-17    Richard Hughes    Version 0.5
  - Added timing definitions for 50Hz mains frequency measured with a logic analyser when running on Arduino Nano.

pcs05.h: 2017-APR-17    Richard Hughes    Version 0.5
  - Added timing definitions for 50Hz mains frequency.

x10.cpp: 2017-APR-17 Richard Hughes Version 0.5
  - Introduced new function detectMainsFreq() called during initialisation to make library work with both 50Hz and 60Hz mains frequencies without user code changes giving the ability for devices using this library to work with 50Hz or 60Hz mains frequencies without modification.
  - Moved definition for receive pin and LED pin to x10.h and removed the zcross_pin definition as this was already defined in x10.h and so duplicated.
  - Enhanced the version function to additionally print the selected mains frequency to serial.
  - Replaced hard coded interrupt number with digitalPinToInterrupt function so that interrupt number is correctly set if a zero crossing pin other than 2 is selected.  May also help this code to run on ESP8266 although this has not been tested.

x10.h:  2017-APR-17 Richard Hughes Version 0.5
  - Added timing variables for bitLength, bitDelay, offsetDelay and halfCycleDelay so that timings can be selected and runtime.
  - Moved definition of receive pin and LED pin from x10.cpp
  - Created new constructor without parameters and moved the init  function to be public so that the class can be created and initialised separately.

### CODE REVIEW

**Comment by DougC** [comment]
Hi Richard,

Thanks for the changes. I haven't used this library for years and I don't have any plans to use it in the future. Would you be willing to take over as the maintainer of this repo?

**Comment by DougC** [comment]
Or at the very least, would you like to be made a commiter?

**Comment by canidorichard** [comment]
Hi Doug,

I am happy to be a committer or take over as maintainer of the repo if you prefer.  

I don't expect that too many people will be looking to start anything new with X10 it is just that I had some X10 light switches that were not much use after the last of my CM15 controllers packed up.  I never got around to changing them out and then came across a TW7223 in a box of bits when I was tidying and thought it might be interesting to make a MQTT to X10 bridge and link into my current automation solution since I had the parts.

I had thrown out a load of plug in X10 modules when the CM15 packed up so it is pretty much only the wall switches I have left.

X10 modules are still sold in a few places in UK and so possibly this could still have a little life left in it.

Cheers

Richard

**Comment by DougC** [comment]
Ok, I've added you as a collaborator. Yeah, X10 seems to be pretty much dying out. I really only use it now for one project, which involves triggering a pump off of motion detectors, and I'm considering changing that to use Zigbee or Z-Wave.

**Pull request merged**
